add_lunch_combo cyanogen_ace-eng
add_lunch_combo cyanogen_beni-eng
add_lunch_combo cyanogen_blade-eng
add_lunch_combo cyanogen_callisto-eng
add_lunch_combo cyanogen_cooper-eng
add_lunch_combo cyanogen_crespo-eng
add_lunch_combo cyanogen_galaxy5-eng
add_lunch_combo cyanogen_gio-eng
add_lunch_combo cyanogen_generic-eng
add_lunch_combo cyanogen_p350-eng
add_lunch_combo cyanogen_p500-eng
add_lunch_combo cyanogen_tass-eng
add_lunch_combo cyanogen_u8150-eng

