PRODUCT_VERSION_MAJOR = 7
PRODUCT_VERSION_MINOR = 2
PRODUCT_VERSION_MAINTENANCE = 0-RC0

CM_VERSION := CyanMobile-eXperience$(PRODUCT_VERSION_DEVICE_SPECIFIC)-$(PRODUCT_RELEASE_NAME)-$(shell date +%Y%m%d)-Release

PRODUCT_BUILD_PROP_OVERRIDES += BUILD_DISPLAY_ID=GWK74

PRODUCT_PROPERTY_OVERRIDES += \
    ro.cm.version=$(CM_VERSION) \
    ro.modversion=$(CM_VERSION)


